name: ci
on: push
jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - run: sbt compile
